dubbo:
  application:
    name: boot-dubbo-provider
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://${zookeeper.address:172.18.12.144}:2181
  provider:
    token: false

zookeeper:
  address: 172.18.12.144